apiVersion: apps/v1
kind: Deployment
metadata:
  name: grades-service
spec:
  selector:
    matchLabels:
      app: grades-service
  replicas: 2
  template:
    metadata:
      labels:
        app: grades-service
    spec:
      containers:
      - name: grades-service
        image: adeel271/grades-service:latest   # Replace with your actual image
        ports:
        - containerPort: 3001
        env:
          - name: MONGO_URI
            value: "mongodb://mongo:27017/grades_db"  # URI pointing to MongoDB service
---
apiVersion: v1
kind: Service
metadata:
  name: grades-service
spec:
  type: ClusterIP              # Internal access only
  selector:
    app: grades-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
